FROM python:3.9-slim

RUN python3 -m pip install poetry==1.4.2

RUN useradd -m -s /bin/bash my_user \
    && echo "my_user:password" | chpasswd \
    && usermod -aG sudo my_user

COPY . /home/my_user/app
WORKDIR /home/my_user/app
RUN chown -R my_user:my_user /home/my_user/app

USER my_user

RUN poetry install
RUN poetry run pytest -v