name: docker_linux
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
        fail-fast: false
    steps:
        - uses: actions/checkout@v3
        - name: Run Docker
          run: |
            make test_linux